//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 進銷存系統
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品列表
    {
        public byte 廠商ID { get; set; }
        public byte 商品類型ID { get; set; }
        public short 商品ID { get; set; }
        public string 商品名稱 { get; set; }
        public decimal 進貨價 { get; set; }
        public decimal 零售價 { get; set; }
    
        public virtual 商品類型列表 商品類型列表 { get; set; }
        public virtual 廠商列表 廠商列表 { get; set; }
    }
}
