//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 進銷存系統
{
    using System;
    using System.Collections.Generic;
    
    public partial class 廠商列表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 廠商列表()
        {
            this.商品列表 = new HashSet<商品列表>();
            this.進貨單列表 = new HashSet<進貨單列表>();
        }
    
        public byte 廠商ID { get; set; }
        public string 廠商名稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 代表人姓名 { get; set; }
        public Nullable<decimal> 資本總額 { get; set; }
        public string 聯絡電話 { get; set; }
        public string 顯示與否 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<商品列表> 商品列表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<進貨單列表> 進貨單列表 { get; set; }
    }
}
