//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 進銷存系統
{
    using System;
    using System.Collections.Generic;
    
    public partial class 進貨單明細
    {
        public int 進貨單編號 { get; set; }
        public byte 商品類型ID { get; set; }
        public short 商品ID { get; set; }
        public short 商品數量 { get; set; }
        public Nullable<decimal> 進貨成本 { get; set; }
        public string 備註 { get; set; }
    
        public virtual 進貨單列表 進貨單列表 { get; set; }
    }
}
